//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int IdEducation { get; set; }
        public string EducationalInstitution { get; set; }
        public System.DateTime FinishEducation { get; set; }
        public int IdQualification { get; set; }
        public int IdDirectionOrSpecialty { get; set; }
        public string EducationCode { get; set; }
    
        public virtual DirectionOrSpecialty DirectionOrSpecialty { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
