//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringTransfersOtherJobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HiringTransfersOtherJobs()
        {
            this.HiringRetraining = new HashSet<HiringRetraining>();
        }
    
        public int IdHiringTransfersOtherJobs { get; set; }
        public System.DateTime Date { get; set; }
        public int IdDepartment { get; set; }
        public int IdPosition { get; set; }
        public decimal Salary { get; set; }
        public string Reason { get; set; }
        public string Signature { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiringRetraining> HiringRetraining { get; set; }
    }
}
