//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringRetraining
    {
        public int HiringRetrainingId { get; set; }
        public int IdHiringTransfersOtherJobs { get; set; }
        public int IdProfessionalRetraining { get; set; }
        public int IdPosition { get; set; }
    
        public virtual HiringTransfersOtherJobs HiringTransfersOtherJobs { get; set; }
        public virtual Position Position { get; set; }
        public virtual ProfessionalRetraining ProfessionalRetraining { get; set; }
    }
}
