//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKnowledge
    {
        public int IdLanguageKnowledge { get; set; }
        public string LanguageKnowledgeTitle { get; set; }
        public int IdLanguageKnowledgeType { get; set; }
        public int LanguageKnowledgeCode { get; set; }
    }
}
