//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionAndDismissal> AdmissionAndDismissal { get; set; }
        public virtual DbSet<BenefitDocument> BenefitDocument { get; set; }
        public virtual DbSet<Benefits> Benefits { get; set; }
        public virtual DbSet<BenefitsFooting> BenefitsFooting { get; set; }
        public virtual DbSet<Certification> Certification { get; set; }
        public virtual DbSet<CertificationDocument> CertificationDocument { get; set; }
        public virtual DbSet<Citizenship> Citizenship { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompositionProfile> CompositionProfile { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DirectionOrSpecialty> DirectionOrSpecialty { get; set; }
        public virtual DbSet<Dismissal> Dismissal { get; set; }
        public virtual DbSet<DismissalReason> DismissalReason { get; set; }
        public virtual DbSet<DocumentAboutEducation> DocumentAboutEducation { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationTitle> EducationTitle { get; set; }
        public virtual DbSet<EligibilityCategory> EligibilityCategory { get; set; }
        public virtual DbSet<EmploymentContract> EmploymentContract { get; set; }
        public virtual DbSet<FamilyComposition> FamilyComposition { get; set; }
        public virtual DbSet<HiringTransfersOtherJobs> HiringTransfersOtherJobs { get; set; }
        public virtual DbSet<HRworker> HRworker { get; set; }
        public virtual DbSet<KindWork> KindWork { get; set; }
        public virtual DbSet<LanguageKnowledge> LanguageKnowledge { get; set; }
        public virtual DbSet<LanguageKnowledgeType> LanguageKnowledgeType { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<MilitaryCommissariat> MilitaryCommissariat { get; set; }
        public virtual DbSet<MilitaryRank> MilitaryRank { get; set; }
        public virtual DbSet<MilitaryRecords> MilitaryRecords { get; set; }
        public virtual DbSet<PersonalCard> PersonalCard { get; set; }
        public virtual DbSet<PlaceBirth> PlaceBirth { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<ProfessionalDevelopment> ProfessionalDevelopment { get; set; }
        public virtual DbSet<ProfessionalDevelopmentDocumentation> ProfessionalDevelopmentDocumentation { get; set; }
        public virtual DbSet<ProfessionalDevelopmentType> ProfessionalDevelopmentType { get; set; }
        public virtual DbSet<ProfessionalRetraining> ProfessionalRetraining { get; set; }
        public virtual DbSet<ProfessionalRetrainingDocument> ProfessionalRetrainingDocument { get; set; }
        public virtual DbSet<ProfessionalRetrainingHiringTransfersOtherJobs> ProfessionalRetrainingHiringTransfersOtherJobs { get; set; }
        public virtual DbSet<Qualification> Qualification { get; set; }
        public virtual DbSet<RewardDocument> RewardDocument { get; set; }
        public virtual DbSet<Rewards> Rewards { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<StockCategory> StockCategory { get; set; }
        public virtual DbSet<TypeWork> TypeWork { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacation> Vacation { get; set; }
        public virtual DbSet<VacationType> VacationType { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkExperience> WorkExperience { get; set; }
        public virtual DbSet<WorkExperienceBonus> WorkExperienceBonus { get; set; }
        public virtual DbSet<WorkExperienceContinuous> WorkExperienceContinuous { get; set; }
        public virtual DbSet<WorkExperienceTotal> WorkExperienceTotal { get; set; }
    }
}
