//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalRetrainingHiringTransfersOtherJobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessionalRetrainingHiringTransfersOtherJobs()
        {
            this.ProfessionalRetraining = new HashSet<ProfessionalRetraining>();
        }
    
        public int IdPosition { get; set; }
    
        public virtual HiringTransfersOtherJobs HiringTransfersOtherJobs { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalRetraining> ProfessionalRetraining { get; set; }
        public virtual ProfessionalRetraining ProfessionalRetraining1 { get; set; }
    }
}
