//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalDevelopment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessionalDevelopment()
        {
            this.PersonalCard = new HashSet<PersonalCard>();
        }
    
        public int IdProfessionalDevelopment { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int IdProfessionalDevelopmentType { get; set; }
        public int IdProfessionalDevelopmentDocumentation { get; set; }
        public string Footing { get; set; }
        public string NameEducationalInstitution { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalCard> PersonalCard { get; set; }
        public virtual ProfessionalDevelopmentDocumentation ProfessionalDevelopmentDocumentation { get; set; }
        public virtual ProfessionalDevelopmentType ProfessionalDevelopmentType { get; set; }
    }
}
