//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacation()
        {
            this.PersonalCard = new HashSet<PersonalCard>();
        }
    
        public int IdVacation { get; set; }
        public int IdVacationType { get; set; }
        public System.DateTime WorkStart { get; set; }
        public System.DateTime WorkFinish { get; set; }
        public int CountVacationDays { get; set; }
        public System.DateTime VacationStart { get; set; }
        public System.DateTime VacationFinish { get; set; }
        public string Footing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalCard> PersonalCard { get; set; }
        public virtual VacationType VacationType { get; set; }
    }
}
