//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int IdWorker { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int IdPlaceBirth { get; set; }
        public int IdCitizenship { get; set; }
        public int IdLanguageKnowledge { get; set; }
        public int IdEducation { get; set; }
        public int IdProfession { get; set; }
        public int IdWorkExperience { get; set; }
        public int IdMaritalStatus { get; set; }
        public int IdFamilyComposition { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime PassportDateIssue { get; set; }
        public string PassportAddress { get; set; }
        public string ActualAddress { get; set; }
        public string PassportAddressIndex { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string NumberPhone { get; set; }
        public int IdPersonalCard { get; set; }
        public string ActualAddressIndex { get; set; }
        public string ServiceNumber { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public int IdSex { get; set; }
        public int IdMilitaryRegistration { get; set; }
        public string PassportGet { get; set; }
        public int UsersId { get; set; }
        public int BirthDateCode { get; set; }
        public int IdQualification { get; set; }
    
        public virtual PersonalCard PersonalCard { get; set; }
        public virtual Users Users { get; set; }
        public virtual WorkExperience WorkExperience { get; set; }
    }
}
