//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkExperience()
        {
            this.Worker = new HashSet<Worker>();
        }
    
        public int IdWorkExperience { get; set; }
        public System.DateTime WorkExperienceDate { get; set; }
        public int IdWorkExperienceTotal { get; set; }
        public int IdWorkExperienceContinuous { get; set; }
        public int IdWorkExperienceBonus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Worker { get; set; }
        public virtual WorkExperienceBonus WorkExperienceBonus { get; set; }
        public virtual WorkExperienceContinuous WorkExperienceContinuous { get; set; }
        public virtual WorkExperienceTotal WorkExperienceTotal { get; set; }
    }
}
