//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCard
    {
        public int IdWorkCard { get; set; }
        public int IdCompany { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ServiceNumber { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string FirstLetter { get; set; }
        public int IdKindWork { get; set; }
        public int IdTypeWork { get; set; }
        public int IdSex { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string DateBirthCode { get; set; }
        public int IdPlaceBirth { get; set; }
        public string PlaceBirthCode { get; set; }
        public int IdCitizenship { get; set; }
        public string CitizenshipCode { get; set; }
        public int IdLanguageName { get; set; }
        public string LanguageNameCode { get; set; }
        public int IdLanguageKnowledgeType { get; set; }
        public int EducationTitleId { get; set; }
        public string EducationTitleCode { get; set; }
        public int IdProfession { get; set; }
        public string ProfessionCode { get; set; }
        public System.DateTime WorkExpDate { get; set; }
        public string WorkExpTotalDays { get; set; }
        public string WorkExpTotalMonths { get; set; }
        public string WorkExpTotalYears { get; set; }
        public string WorkExpConDays { get; set; }
        public string WorkExpConMonths { get; set; }
        public string WokrExpConYears { get; set; }
        public string WorkExpBonusDays { get; set; }
        public string WorkExpBounsMonths { get; set; }
        public string WorkExpBonusYears { get; set; }
        public int IdMaritalStatus { get; set; }
        public string MaritalStatusCode { get; set; }
        public int IdFamilyComposition { get; set; }
        public string FamilyCompositionLastName { get; set; }
        public string FamilyCompositionName { get; set; }
        public string FamilyCompositionMiddleName { get; set; }
        public System.DateTime FamilyCompositionBirthDate { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime PassportGetDate { get; set; }
        public string PassportWhoGet { get; set; }
        public string ActualAddressIndex { get; set; }
        public string ActualAddress { get; set; }
        public string PassportIndex { get; set; }
        public string PassportAddress { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string PhoneNumber { get; set; }
        public string TitleCompanyCode { get; set; }
        public string DirectionOrSpecialtyCode { get; set; }
    
        public virtual Citizenship Citizenship { get; set; }
        public virtual Company Company { get; set; }
        public virtual EducationTitle EducationTitle { get; set; }
        public virtual FamilyComposition FamilyComposition { get; set; }
        public virtual KindWork KindWork { get; set; }
        public virtual LanguageKnowledgeType LanguageKnowledgeType { get; set; }
        public virtual LanguageName LanguageName { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        public virtual PlaceBirth PlaceBirth { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual TypeWork TypeWork { get; set; }
    }
}
